paths:
  work_root: "abaqusWF"
  results_root: "results"
problem:
  parameters: ['h1', 'h2', 'h3', 'h2_3rd_layer', 'cell_height_1st_layer', 'fillet_a', 'fillet_b', 'fillet_c', 'assymetry_1st_layer', 'arc_offset']
  objectives: ['']
geometry:
  diameter: 26.0
  h1: (0.1, 1)
  h2: (0.1, 1)
  h3: (0.1, 1)
  h2_3rd_layer: (1, 6)
  width_low_cut: 0.5
  cell_height_1st_layer: (1, 10)
  repeat: 12
  fillet_a: (0, 1)
  fillet_b: (0, 1)
  fillet_c: (0, 1)
  assymetry_1st_layer: (0, 1)
  padding: 0.5
  arc_offset: (-1, 1)
material: # via https://pmc.ncbi.nlm.nih.gov/articles/PMC12085968/
  name: "Niti"
  EM: 35000.0
  Poisson: 0.33
  material_model: 'superelastic'
  superelastic:
    EA: 24000.0
    nuA: 0.33
    nuM: 0.30
    sig_s_AS: 250  # sigma_s_AS, sigma_f_AS  (loading tension: start/end)
    sig_f_AS: 270
    sig_s_SA: 40  # sigma_s_SA, sigma_f_SA  (unloading: start/end)
    sig_f_SA: 20
    sig_s_AC: 900  # sigma_s_AC (compression loading start)
    eps_L: 0.04
    eps_V: 0.00  # eps_V (несвязанный поток); 0.0 => связанный)
    T0: 37.0 # T0 (°C)
    dSig_dT_L_per_C: 6.527  # dSig_dT_L, dSig_dT_U (MPa/°C)
    dSig_dT_U_per_C: 6.527
solver:
  job_name_prefix: "tavr_case"
  step_name: "Step-Load"
  step_time: 1
  cpus: 8
  outputs:
    field_outputs: ["S", "U", "LE"]
    time_interval: 0.025
    history_outputs: []
    frame_index_for_metric: last
hydra:
  run:
    dir: .
